kind: pipeline
type: exec
name: telegram-test

clone:
  disable: true

steps:
# test env
  - name: test telebot message
    image: yitan/tools:ddt
    settings:
      token: abc548387700a5041e923a17066eecbc9f4e8ea98a284494c19e8e1bb10cb5c7
      type: markdown
      debug: true
      tips_title: "drone_msg"
      message_color: true
      message_pic: true
      sha_link: true

---
kind: pipeline
type: exec
name: telegram-test

platform:
  os: windows
  arch: amd64

steps:
  - name: exec build
    command:
      - echo 1