kind: pipeline
type: docker
name: telegram-test

steps:
# test env
  - name: test telebot message
    image: yitan/tools:ddt
    settings:
      token: 3a15e84a03136e9863cbfa237a74ba528a66db89b8e74e141676d6bc1943c2b6
      type: markdown
      debug: true
      tips_title: "drone_msg"
      message_color: true
      message_pic: true
      sha_link: true